VIRTUAL_WIDTH = 224
VIRTUAL_HEIGHT = 256

WINDOW_WIDTH = VIRTUAL_WIDTH * 3
WINDOW_HEIGHT = VIRTUAL_HEIGHT * 3

ALIEN_SIZE = 12

SHIP_SPEED = 100

ALIENS_WIDE = 11
ALIENS_TALL = 5
ALIEN_MOVEMENT_INTERVAL = 0.7
ALIEN_STEP_LENGTH = 5
ALIEN_STEP_HEIGHT = 8

FAR_RIGHT_ALIEN = 11
FAR_LEFT_ALIEN = 1

PROJECTILE_WIDTH = 1
PROJECTILE_LENGTH = 5
PROJECTILE_SPEED = 120